//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public int Id { get; set; }
        public string ContractNo { get; set; }
        public Nullable<decimal> TotalValue { get; set; }
        public Nullable<System.DateTime> SubmitDate { get; set; }
        public Nullable<decimal> Paid { get; set; }
        public Nullable<decimal> Debt { get; set; }
        public string PartnerName { get; set; }
        public int Partner { get; set; }
        public bool IsSale { get; set; }
        public bool IncludedVat { get; set; }
    }
}
