//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductOfContract
    {
        public int Id { get; set; }
        public int ContractId { get; set; }
        public int ProductId { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
    }
}
